name: Web Application Deployment
on: push
jobs:
  build-and-deploy: 
    runs-on: ubuntu-latest
    permissions:
      id-token: write      # ← REQUIRED for OIDC
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
      - name: Install dependencies
        run: composer install --no-dev --prefer-dist --optimize-autoloader
      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/gh-actions-admin-role
          aws-region: us-east-1 
      - name: execute sonar-scanner
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_KEY: ${{ secrets.SONAR_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker build
        run: docker build -t webapp:latest .
      - name: Docker push
        run: |
          docker tag webapp:latest 211125304367.dkr.ecr.us-east-1.amazonaws.com/webapp:latest && 
          docker push 211125304367.dkr.ecr.us-east-1.amazonaws.com/webapp:latest
      - name: Deploy to S3
        run: |
          aws s3 sync . s3://alb-s3-webapp-html --exclude ".git/*" --exclude "node_modules/*" --exclude "vendor/*" --delete