name: Web Application Deployment
on: push
jobs:
  build-and-deploy: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
      - name: Install dependencies
        run: composer install --no-dev --prefer-dist --optimize-autoloader
      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::211125304367:role/gh-actions-admin-role
          aws-region: us-east-1 
      - name: Verify AWS identity
        run: aws sts get-caller-identity
      - name: Deploy to production
        if: github.ref == 'refs/heads/main'
        run: |
          aws s3 sync . s3://alb-s3-webapp-html --exclude ".git/*" --exclude "node_modules/*" --exclude "vendor/*" --delete